export enum VideoFileExtension {
  _3GP = "3gp",
  ASF = "asf",
  AVI = "avi",
  F4V = "f4v",
  FLV = "flv",
  HEVC = "hevc",
  M2TS = "m2ts",
  M2V = "m2v",
  M4V = "m4v",
  MJPEG = "mjpeg",
  MKV = "mkv",
  MOV = "mov",
  MP4 = "mp4",
  MPEG = "mpeg",
  MPG = "mpg",
  MTS = "mts",
  MXF = "mxf",
  OGV = "ogv",
  RM = "rm",
  TS = "ts",
  VOB = "vob",
  WEBM = "webm",
  WMV = "wmv",
  WTV = "wtv",
}

export enum AudioFileExtension {
  MP3 = "mp3",
}
